// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amessage.proto

#ifndef PROTOBUF_amessage_2eproto__INCLUDED
#define PROTOBUF_amessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_amessage_2eproto();
void protobuf_AssignDesc_amessage_2eproto();
void protobuf_ShutdownFile_amessage_2eproto();

class AMessage;

//int eeee;
class test {
public:
  int ff;
  int gg;
};


// ===================================================================

class AMessage : public ::google::protobuf::Message {
 public:
  AMessage();
  virtual ~AMessage();

  AMessage(const AMessage& from);

  inline AMessage& operator=(const AMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AMessage& default_instance();

  void Swap(AMessage* other);

  // implements Message ----------------------------------------------

  AMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AMessage& from);
  void MergeFrom(const AMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 a = 1;
  inline bool has_a() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline ::google::protobuf::int32 a() const;
  inline void set_a(::google::protobuf::int32 value);

  // optional int32 b = 2;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 2;
  inline ::google::protobuf::int32 b() const;
  inline void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:AMessage)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_b();
  inline void clear_has_b();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_amessage_2eproto();
  friend void protobuf_AssignDesc_amessage_2eproto();
  friend void protobuf_ShutdownFile_amessage_2eproto();

  void InitAsDefaultInstance();
  static AMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// AMessage

// required int32 a = 1;
inline bool AMessage::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AMessage::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AMessage::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AMessage::clear_a() {
  a_ = 0;
  clear_has_a();
}
inline ::google::protobuf::int32 AMessage::a() const {
  return a_;
}
inline void AMessage::set_a(::google::protobuf::int32 value) {
  set_has_a();
  a_ = value;
}

// optional int32 b = 2;
inline bool AMessage::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AMessage::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AMessage::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AMessage::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 AMessage::b() const {
  return b_;
}
inline void AMessage::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_amessage_2eproto__INCLUDED
